version: '3.8'

services:
  interestrateapi:
    image: interestrateapi
    build:
      dockerfile: ./src/Soft.InterestRate.API/Dockerfile
      context: .
    ports:
      - "5001:5001"
    networks:
      - interest-rate
    depends_on:
      - "interestratequeryapi"
  
  interestratequeryapi:
      image: interestratequeryapi
      build:
        dockerfile: ./src/Soft.InterestRate.Query.API/Dockerfile
        context: .
      ports:
        - "5000:5000"
      networks:
        - interest-rate

networks:
    interest-rate:
        driver: bridge