version: '3.7'

services:
  interestratequeryapi:
      image: interestratequeryapi
      build:
        context: .
        dockerfile: ./src/Soft.InterestRate.Query.API/Dockerfile
      environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://0.0.0.0:5000
      ports:
        - "5000:5000"
      networks:
        - interest-rate
        
  interestrateapi:
        image: interestrateapi
        build:
          context: .
          dockerfile: ./src/Soft.InterestRate.API/Dockerfile
        environment:
          - ASPNETCORE_ENVIRONMENT=Production
          - ASPNETCORE_URLS=http://0.0.0.0:5001
        ports:
          - "5001:5001"
        networks:
          - interest-rate

networks:
    interest-rate:
        driver: bridge